services:
  scraper:
    build: 
      context: ./
      dockerfile: ./scraper/Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgresql://postgres/sreality_db?user=user&password=password
    
  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=postgresql://postgres/sreality_db?user=user&password=password

  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=sreality_db
