services:
  scraper:
    build: scraper
    environment:
      - POSTGRES_URL=postgresql://postgres/sreality_db?user=user&password=password
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=sreality_db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 9090:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=password